---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echov
  namespace: demo
  labels:
    app: echov
  annotations:
    flux.weave.works/automated: "true"
    # flux.weave.works/tag.[container_name]
    # flux.weave.works/tag.echo-version: regexp:^1.*
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: echov
  template:
    metadata:
      labels:
        app: echov
    spec:
      containers:
      - name: echo-version
        image: rammusxu/echo-version:1.0.2
        imagePullPolicy: IfNotPresent
